# Generated by Django 5.1.6 on 2025-10-14 21:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0005_delete_propriete'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom de la propriété')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Propriété',
                'verbose_name_plural': 'Propriétés',
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('full_name', models.CharField(blank=True, max_length=200, verbose_name='Nom complet')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Titre/Profession')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Format de téléphone invalide', regex='^\\+?[\\d\\s\\-\\(\\)]+$')], verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('id_number', models.CharField(blank=True, max_length=50, verbose_name='Numéro CNI/Passeport')),
                ('location', models.CharField(blank=True, help_text='Ex: Cocody, Abidjan', max_length=200, verbose_name='Localisation')),
                ('lease_start_date', models.DateField(verbose_name='Date début du bail')),
                ('lease_end_date', models.DateField(blank=True, help_text='Laisser vide si durée indéterminée', null=True, verbose_name='Date fin du bail')),
                ('contract_status', models.CharField(choices=[('actif', 'Actif'), ('en_attente', 'En attente'), ('expire', 'Expiré'), ('resilie', 'Résilié')], default='en_attente', max_length=20, verbose_name='Statut du contrat')),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Loyer mensuel (FCFA)')),
                ('security_deposit', models.CharField(blank=True, help_text='Ex: 1 mois de loyer, 2 mois de loyer', max_length=100, verbose_name='Dépôt de garantie')),
                ('payment_method', models.CharField(blank=True, choices=[('mobile_money', 'Mobile Money'), ('virement', 'Virement bancaire'), ('especes', 'Espèces'), ('cheque', 'Chèque'), ('orange_money', 'Orange Money'), ('mtn_money', 'MTN Money')], max_length=30, verbose_name='Mode de paiement')),
                ('payment_status', models.CharField(choices=[('a_jour', 'À jour'), ('impaye', 'Impayé'), ('retard', 'En retard'), ('en_attente', 'En attente')], default='en_attente', max_length=20, verbose_name='Statut de paiement')),
                ('next_payment', models.DateField(blank=True, null=True, verbose_name='Prochain paiement')),
                ('last_payment', models.DateField(blank=True, null=True, verbose_name='Dernier paiement')),
                ('payments_count', models.IntegerField(default=0, verbose_name='Nombre de paiements effectués')),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total payé (FCFA)')),
                ('reliability', models.IntegerField(default=0, help_text='Pourcentage de fiabilité du locataire', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Fiabilité (%)')),
                ('signed_contract', models.FileField(blank=True, help_text='PDF, JPG ou PNG', null=True, upload_to='contracts/', verbose_name='Contrat signé')),
                ('id_document', models.FileField(blank=True, help_text='CNI, Passeport', null=True, upload_to='identity_documents/', verbose_name="Justificatif d'identité")),
                ('additional_notes', models.TextField(blank=True, help_text='Préférences, conditions spéciales, etc.', verbose_name='Notes complémentaires')),
                ('avatar', models.CharField(blank=True, editable=False, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('linked_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to='backend_app.property', verbose_name='Propriété liée')),
            ],
            options={
                'verbose_name': 'Locataire',
                'verbose_name_plural': 'Locataires',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['payment_status'], name='backend_app_payment_90869b_idx'), models.Index(fields=['contract_status'], name='backend_app_contrac_b45d6b_idx')],
            },
        ),
    ]
