# Generated by Django 5.1.6 on 2025-10-14 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0006_property_tenant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='tenant',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name='Nom complet'),
        ),
    ]
